# This file was generated by GoReleaser. DO NOT EDIT.
cask "fh" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "fh"], chdir: "."
    end
  end

  version "1.1"

  on_macos do
    on_arm do
      sha256 "183840b267a773ba8a746771d3654b4f72e87d7d4eb930da9bf1f31c7fa49f7c"
      url "https://downloads.factorhouse.io/fh/v#{version}/fh_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "476a2b0b435cf70f1ef582a83d1a2300a4999d9be64244438dada662f6121d7f"
      url "https://downloads.factorhouse.io/fh/v#{version}/fh_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8de83412aba1f5e8c101e8cc9c43a0cceab777221b7e8a06e3801528ea2f4f7e"
      url "https://downloads.factorhouse.io/fh/v#{version}/fh_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f0da7c72cfaf46016f0bd0f66297d086dc8af02b7044fb5d9f39ccdeed90542c"
      url "https://downloads.factorhouse.io/fh/v#{version}/fh_#{version}_linux_amd64.tar.gz"
    end
  end

  name "fh"
  desc "Factor House command-line interface for Kpow, Flex, Iglu and Factor Platform"
  homepage "https://factorhouse.io/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fh"

  # No zap stanza required
end
