# This file was generated by GoReleaser. DO NOT EDIT.
cask "fh" do
  version "0.7.0"

  on_macos do
    on_arm do
      sha256 "bc200546faee45a552d1393ce48650da915dcaaad8c9caed8d46c32ed4cd1425"
      url "https://downloads.factorhouse.io/fh/v#{version}/fh_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "da7608023cf3c137888ff3f13948e692bd1afedcc81bcb4b276ef15cdc2b973d"
      url "https://downloads.factorhouse.io/fh/v#{version}/fh_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a4be25feafb1c3270b7b1c9432db013eab88fbbc2b77ea01e2844866a9c6a13d"
      url "https://downloads.factorhouse.io/fh/v#{version}/fh_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5d352e5f1c4aebeb2b8710ed6dddae31dbb23cc72be5558292f521b4345324f6"
      url "https://downloads.factorhouse.io/fh/v#{version}/fh_#{version}_linux_amd64.tar.gz"
    end
  end

  name "fh"
  desc "Factor House command-line interface for Kpow, Flex, Iglu and Factor Platform"
  homepage "https://factorhouse.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fh"]
    end
  end

  # No zap stanza required
end
