# This file was generated by GoReleaser. DO NOT EDIT.
cask "fh" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "fh"], chdir: "."
    end
  end

  version "1.0"

  on_macos do
    on_arm do
      sha256 "f3705d1d8fa14a729c6edade9f10e24469a313d30aeac0b7e7885df1d2a0288e"
      url "https://downloads.factorhouse.io/fh/v#{version}/fh_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "528774bdb9fb3e8012469d50c1f6506531d03590c6a8acb1376ff89bd9234c24"
      url "https://downloads.factorhouse.io/fh/v#{version}/fh_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c661a03781d562e6fbb9c50451192bf055b00f7f5f5130bd9270f76a2cdc0960"
      url "https://downloads.factorhouse.io/fh/v#{version}/fh_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c90ead32c3a8828b4b7a10dbc417ca35ef08714a467f6eccec43125d37502403"
      url "https://downloads.factorhouse.io/fh/v#{version}/fh_#{version}_linux_amd64.tar.gz"
    end
  end

  name "fh"
  desc "Factor House command-line interface for Kpow, Flex, Iglu and Factor Platform"
  homepage "https://factorhouse.io/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fh"

  # No zap stanza required
end
