# This file was generated by GoReleaser. DO NOT EDIT.
cask "kpow" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "9cbdc574d37cfbf564434ff75377d7f1c3821b39eba9da4bb648da7b9136ebab"
      url "https://github.com/factorhouse/factor-cli/releases/download/v#{version}/kpow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2096d3304a8d5780099afddbcd1727b2f43a89f071c1d4970a97ec11f626b8ef"
      url "https://github.com/factorhouse/factor-cli/releases/download/v#{version}/kpow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "994b975f03eeac158817da3f65d95f28ef637452922562aac8dd19b6c58d62ab"
      url "https://github.com/factorhouse/factor-cli/releases/download/v#{version}/kpow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d623f5feb4f4b997bc0d644d31fa7b5ac07273fc607e608deb58f802cbdb1a3e"
      url "https://github.com/factorhouse/factor-cli/releases/download/v#{version}/kpow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kpow"
  desc "Single-binary CLI for the Kpow Kafka management REST API"
  homepage "https://kpow.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kpow"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kpow"]
    end
  end

  # No zap stanza required

end
