# This file was generated by GoReleaser. DO NOT EDIT.
cask "kpow" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "d565dddf5f3e7b08968b7178bcdb255a1411111db82479343bbc90e334dfedf4"
      url "https://github.com/factorhouse/factor-cli/releases/download/v#{version}/kpow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e5908c641a9e9c1f8c835927a8c163994b97351294b91a241a808c6dfd93bc86"
      url "https://github.com/factorhouse/factor-cli/releases/download/v#{version}/kpow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d416dd41a10061f20cf2e5b632d26d98089538761a5199cbd12cf1dda003eab5"
      url "https://github.com/factorhouse/factor-cli/releases/download/v#{version}/kpow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c3395afd74f1c4e79c8addc8185eeb64f350be60c506053967a5b794bc2a6300"
      url "https://github.com/factorhouse/factor-cli/releases/download/v#{version}/kpow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kpow"
  desc "Single-binary CLI for the Kpow Kafka management REST API"
  homepage "https://kpow.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kpow"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kpow"]
    end
  end

  # No zap stanza required

end
