# This file was generated by GoReleaser. DO NOT EDIT.
cask "kpow" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "f137baf90f5a6728632efd24d5cea00f9e3eb29177ba80092f2843398a67761b"
      url "https://github.com/factorhouse/factor-cli/releases/download/v#{version}/kpow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ccca5908520c89fae4118e1bcf8df2d4ffce106996b11848ec8d19d08cbb7dd5"
      url "https://github.com/factorhouse/factor-cli/releases/download/v#{version}/kpow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "321ae517dc300ed6672391d0ed311c4201d9a97238159a85871192eee027bc32"
      url "https://github.com/factorhouse/factor-cli/releases/download/v#{version}/kpow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8ea75c354c8ca86efe928bb67f8ab5c4dff28327aa05341f3db8f3a8e464a4d8"
      url "https://github.com/factorhouse/factor-cli/releases/download/v#{version}/kpow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kpow"
  desc "Single-binary CLI for the Kpow Kafka management REST API"
  homepage "https://kpow.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kpow"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kpow"]
    end
  end

  # No zap stanza required

end
